
import { Property, Testimonial, User, UserType } from './types';

export const QR_BASE_URL = 'https://www.toletbro.com/properties/qrcode';

export const MODELS = {
  TEXT: 'gemini-3.1-pro-preview',
  IMAGE_GEN: 'gemini-2.5-flash-image',
  IMAGE_EDIT: 'gemini-2.5-flash-image',
  MAPS: 'gemini-2.5-flash'
};

export const ASPECT_RATIOS = [
  '1:1', '2:3', '3:2', '3:4', '4:3', '9:16', '16:9', '21:9'
];

export const MOCK_USERS: User[] = [
  {
    id: 'owner-1',
    name: 'Robert Fox',
    phone: '+1 234 567 8901',
    type: UserType.OWNER,
    qrCode: 'ABC123',
    primaryPhoneEnabled: true,
    showCallMessage: true,
    callMessageText: "Please contact me only after viewing the home images and details. All details provided are genuine. No negotiation. Vegetarian tenants preferred. Please contact only if you are serious.",
    ownerTags: ["Vegetarian Only", "No Negotiation", "Serious Buyers Only"]
  },
  {
    id: 'owner-2',
    name: 'Jane Cooper',
    phone: '+1 234 567 8902',
    type: UserType.OWNER,
    qrCode: 'XYZ987',
    primaryPhoneEnabled: true,
    showCallMessage: false
  }
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah Jenkins',
    role: 'Home Finder',
    content: 'ToletBro made finding my new apartment so easy! The QR scanning feature is brilliant.',
    avatar: 'https://picsum.photos/seed/sarah/100/100'
  },
  {
    id: '2',
    name: 'Michael Chen',
    role: 'Property Owner',
    content: 'I managed to rent out my penthouse in just 3 days using the QR marketing tools.',
    avatar: 'https://picsum.photos/seed/michael/100/100'
  }
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    ownerId: 'owner-1',
    title: '4+ BHK Independent House',
    description: 'A stunning modern villa with private pool and ocean view. Perfect for large families looking for luxury and privacy.',
    price: 4500,
    location: 'Beverly Hills, CA',
    city: 'Beverly Hills',
    state: 'CA',
    locality: 'North Beverly',
    latitude: 34.0736,
    longitude: -118.4004,
    type: 'rent',
    propertyType: 'Independent House',
    bhkType: '4+ BHK',
    furnishing: 'Fully Furnished',
    images: ['https://picsum.photos/seed/villa1/800/600', 'https://picsum.photos/seed/villa2/800/600', 'https://picsum.photos/seed/villa3/800/600'],
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3200,
    floorNo: 0,
    totalFloors: 2,
    amenities: ['Lift', 'Parking', 'Security', 'Pool', 'Gym'],
    nearbyFacilities: ['School', 'Hospital', 'Park'],
    listedBy: 'Owner',
    analytics: {
      totalVisitors: 450,
      smartBoardScans: 120,
      onlineSearches: 330,
      callClicks: 45,
      whatsappClicks: 28
    }
  },
  {
    id: 'prop-2',
    ownerId: 'owner-2',
    title: '2 BHK Apartment',
    description: 'Industrial style loft in the heart of the city. High ceilings and large windows providing ample natural light.',
    price: 850000,
    location: 'Manhattan, NY',
    city: 'Manhattan',
    state: 'NY',
    locality: 'SoHo',
    latitude: 40.7233,
    longitude: -74.0030,
    type: 'buy',
    propertyType: 'Apartment',
    bhkType: '2 BHK',
    furnishing: 'Unfurnished',
    images: ['https://picsum.photos/seed/loft1/800/600', 'https://picsum.photos/seed/loft2/800/600'],
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1500,
    floorNo: 15,
    totalFloors: 40,
    amenities: ['Lift', 'Security', 'Club House'],
    nearbyFacilities: ['Metro', 'Market', 'Cafe'],
    listedBy: 'Agent',
    analytics: {
      totalVisitors: 890,
      smartBoardScans: 310,
      onlineSearches: 580,
      callClicks: 62,
      whatsappClicks: 41
    }
  },
  {
    id: 'prop-3',
    ownerId: 'owner-1',
    title: '1 BHK Apartment',
    description: 'Perfect for single professionals or couples. Compact yet functional design in a prime location.',
    price: 2200,
    location: 'Beverly Hills, CA',
    city: 'Beverly Hills',
    state: 'CA',
    locality: 'North Beverly',
    latitude: 34.0780,
    longitude: -118.4050,
    type: 'rent',
    propertyType: 'Apartment',
    bhkType: '1 BHK',
    furnishing: 'Semi-Furnished',
    images: ['https://picsum.photos/seed/guest1/800/600', 'https://picsum.photos/seed/guest2/800/600'],
    bedrooms: 1,
    bathrooms: 1,
    sqft: 800,
    floorNo: 2,
    totalFloors: 5,
    amenities: ['Parking', 'CCTV'],
    nearbyFacilities: ['Metro', 'Bus Stop', 'Grocery'],
    listedBy: 'Owner',
    analytics: {
      totalVisitors: 210,
      smartBoardScans: 40,
      onlineSearches: 170,
      callClicks: 12,
      whatsappClicks: 15
    }
  },
  {
    id: 'prop-4',
    ownerId: 'owner-2',
    title: '3 BHK Penthouse',
    description: 'Luxurious penthouse with panoramic city views. Features a large terrace and premium finishes throughout.',
    price: 1200000,
    location: 'Chicago, IL',
    city: 'Chicago',
    state: 'IL',
    locality: 'River North',
    latitude: 41.8924,
    longitude: -87.6341,
    type: 'buy',
    propertyType: 'Apartment',
    bhkType: '3 BHK',
    furnishing: 'Fully Furnished',
    images: ['https://picsum.photos/seed/pent1/800/600', 'https://picsum.photos/seed/pent2/800/600'],
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2800,
    floorNo: 45,
    totalFloors: 45,
    amenities: ['Lift', 'Security', 'Pool', 'Terrace Garden'],
    nearbyFacilities: ['River Walk', 'Fine Dining', 'Gallery'],
    listedBy: 'Agent',
    analytics: {
      totalVisitors: 1200,
      smartBoardScans: 450,
      onlineSearches: 750,
      callClicks: 85,
      whatsappClicks: 55
    }
  },
  {
    id: 'prop-5',
    ownerId: 'owner-1',
    title: '2 BHK Independent Floor',
    description: 'Spacious independent floor in a quiet residential neighborhood. Ideal for families seeking a peaceful environment.',
    price: 3500,
    location: 'San Francisco, CA',
    city: 'San Francisco',
    state: 'CA',
    locality: 'Sunset District',
    latitude: 37.7516,
    longitude: -122.4815,
    type: 'rent',
    propertyType: 'Apartment',
    bhkType: '2 BHK',
    furnishing: 'Semi-Furnished',
    images: ['https://picsum.photos/seed/floor1/800/600', 'https://picsum.photos/seed/floor2/800/600'],
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    floorNo: 1,
    totalFloors: 3,
    amenities: ['Parking', 'Garden'],
    nearbyFacilities: ['Beach', 'Park', 'School'],
    listedBy: 'Owner',
    analytics: {
      totalVisitors: 320,
      smartBoardScans: 85,
      onlineSearches: 235,
      callClicks: 22,
      whatsappClicks: 18
    }
  },
  {
    id: 'prop-6',
    ownerId: 'owner-2',
    title: '1 RK Studio',
    description: 'Modern studio apartment perfect for students or young professionals. Well-connected to public transport.',
    price: 1500,
    location: 'Boston, MA',
    city: 'Boston',
    state: 'MA',
    locality: 'Back Bay',
    latitude: 42.3503,
    longitude: -71.0810,
    type: 'rent',
    propertyType: 'Apartment',
    bhkType: '1 RK',
    furnishing: 'Fully Furnished',
    images: ['https://picsum.photos/seed/studio1/800/600'],
    bedrooms: 0,
    bathrooms: 1,
    sqft: 450,
    floorNo: 4,
    totalFloors: 10,
    amenities: ['Lift', 'Laundry', 'Security'],
    nearbyFacilities: ['University', 'Library', 'Subway'],
    listedBy: 'Agent',
    analytics: {
      totalVisitors: 560,
      smartBoardScans: 120,
      onlineSearches: 440,
      callClicks: 35,
      whatsappClicks: 25
    }
  },
  {
    id: 'prop-7',
    ownerId: 'owner-1',
    title: '3 BHK Villa',
    description: 'Beautiful Mediterranean style villa with a private garden and spacious interiors. Located in a gated community.',
    price: 5500,
    location: 'Miami, FL',
    city: 'Miami',
    state: 'FL',
    locality: 'Coral Gables',
    latitude: 25.7214,
    longitude: -80.2684,
    type: 'rent',
    propertyType: 'Independent House',
    bhkType: '3 BHK',
    furnishing: 'Fully Furnished',
    images: ['https://picsum.photos/seed/miami1/800/600', 'https://picsum.photos/seed/miami2/800/600'],
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2400,
    floorNo: 0,
    totalFloors: 2,
    amenities: ['Parking', 'Security', 'Pool', 'Garden'],
    nearbyFacilities: ['Beach', 'Golf Course', 'Mall'],
    listedBy: 'Owner',
    analytics: {
      totalVisitors: 380,
      smartBoardScans: 95,
      onlineSearches: 285,
      callClicks: 30,
      whatsappClicks: 22
    }
  },
  {
    id: 'prop-8',
    ownerId: 'owner-2',
    title: '2 BHK Apartment',
    description: 'Modern apartment with sleek finishes and smart home features. Located in a vibrant neighborhood.',
    price: 650000,
    location: 'Seattle, WA',
    city: 'Seattle',
    state: 'WA',
    locality: 'Capitol Hill',
    latitude: 47.6229,
    longitude: -122.3214,
    type: 'buy',
    propertyType: 'Apartment',
    bhkType: '2 BHK',
    furnishing: 'Semi-Furnished',
    images: ['https://picsum.photos/seed/seattle1/800/600'],
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    floorNo: 8,
    totalFloors: 12,
    amenities: ['Lift', 'Gym', 'Roof Deck'],
    nearbyFacilities: ['Park', 'Coffee Shop', 'Library'],
    listedBy: 'Agent',
    analytics: {
      totalVisitors: 420,
      smartBoardScans: 150,
      onlineSearches: 270,
      callClicks: 40,
      whatsappClicks: 30
    }
  },
  {
    id: 'prop-9',
    ownerId: 'owner-1',
    title: '4 BHK Independent House',
    description: 'Spacious independent house with a large backyard and multiple balconies. Perfect for a growing family.',
    price: 4800,
    location: 'Austin, TX',
    city: 'Austin',
    state: 'TX',
    locality: 'West Lake Hills',
    latitude: 30.2913,
    longitude: -97.8072,
    type: 'rent',
    propertyType: 'Independent House',
    bhkType: '4+ BHK',
    furnishing: 'Unfurnished',
    images: ['https://picsum.photos/seed/austin1/800/600', 'https://picsum.photos/seed/austin2/800/600'],
    bedrooms: 4,
    bathrooms: 4,
    sqft: 3500,
    floorNo: 0,
    totalFloors: 2,
    amenities: ['Parking', 'Security', 'Backyard'],
    nearbyFacilities: ['School', 'Park', 'Hiking Trail'],
    listedBy: 'Owner',
    analytics: {
      totalVisitors: 290,
      smartBoardScans: 60,
      onlineSearches: 230,
      callClicks: 18,
      whatsappClicks: 12
    }
  },
  {
    id: 'prop-10',
    ownerId: 'owner-2',
    title: '1 BHK Studio',
    description: 'Charming studio in a historic building. Features original brick walls and modern appliances.',
    price: 1800,
    location: 'Philadelphia, PA',
    city: 'Philadelphia',
    state: 'PA',
    locality: 'Old City',
    latitude: 39.9500,
    longitude: -75.1417,
    type: 'rent',
    propertyType: 'Apartment',
    bhkType: '1 BHK',
    furnishing: 'Semi-Furnished',
    images: ['https://picsum.photos/seed/philly1/800/600'],
    bedrooms: 1,
    bathrooms: 1,
    sqft: 650,
    floorNo: 3,
    totalFloors: 4,
    amenities: ['Security', 'Laundry'],
    nearbyFacilities: ['Museum', 'Historic Site', 'Cafe'],
    listedBy: 'Agent',
    analytics: {
      totalVisitors: 310,
      smartBoardScans: 80,
      onlineSearches: 230,
      callClicks: 25,
      whatsappClicks: 18
    }
  }
];
